Use `nix show-derivation` to find derivers when `nix-store -qd` fails (#74)
Fixes #69 

* Factor out _find_deriver

* Nicer error message when deriver does not exist

Nicer than
>  subprocess.CalledProcessError: Command '['nix-store', '-qR', '<path>']' returned non-zero exit status 1.
which is what happened when derivers don't exist.

* Rename deriver → qpi_deriver

There are two ways to find derivers, unfortunately.  This method uses
QueryPathInfo.

* Look for derivers with QueryValidDerivers too

* Create _call_nix()

* Pass '--experimental-features nix-command' if needed

New nix versions like 2.4pre20210326_dd77f71 require this flag, but old nix versions like 2.3.10 fail with 'error: unrecognised flag' so we must determine which case we're in and pass it accordingly.

* Test for --experimental-features flag just once