Nicer error message when deriver does not exist
Nicer than
  subprocess.CalledProcessError: Command '['nix-store', '-qR', '<path>']' returned non-zero exit status 1.
which is what happened when derivers don't exist.